language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: and1er
  password:
    secure: Tb0X1tisTDx0CG+40KnCISgUPYS7Ijt7azcBQZ89k1we5EwFOs4tsj0r8cjYubwcdwMMo8sffUQF2RMQYKar5n9aV0x8cx8OfgOzpgF4naIDmc2LDAdkl5QBVeihsNTSWg5Fa2PrvjlKjkV+wmyh3++liqwoTld3IFPKtdOBsvvtLvUElnfiBB6Ef4PcA728by1CfvHzoHVlHo15nla7r7WnZF06jqnHQzJfJiIyVGvmxzkVnf30SmPTdwJGbjfAs6eskjXag2rQDaNKs7Mp1p2i0kpHZ28MxT1vRAPrRztMuB0NPQ65mglC8wI1o/BdJU5FlcoN2y0BCEmMd5Bc1vpHTEUeCDE3fH9EaKpUcf9eK5tL4YEaxP4QxX+iJCtsxdMxD0V2ENNz6Tme8iiSnY8iuCO3V/mLq8l4iwlXhn71vmn+iz/O+V0fr6jlQ86ln5EM7MfXgFhG7J0dsjjk9+QJtYuYkSF9hpJpE5XAX/FO/DIW1mZjZjeNPy1oiv5aAlh31aPe5cwi7eadof4zdExWfYtdNidOC//nN/hwUMgZuD2/V44aBnKd893D5QMEWNpkQkw9sZbKLwXLADR+sG3GSzHB17abX6eaABHTNZs3X1TxHPhZgLqkhDKXP3V7M9JXTSevvPpPIjzvZ6lKZ78Y0BbqSck0UQ4MNrN8Ptw=
  on:
    tags: true
    repo: and1er/python_helpers
    python: 3.8
